config/routes.rb
Rails.application.routes.draw do
  
  resources :categories 
  get '/' => 'sessions#home' 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  post '/signup' => 'users#create' 
  delete '/logout' => 'sessions#destroy'
  get '/most_popular' => 'restaurants#most_popular' 

  get '/auth/:provider/callback' => 'sessions#create'
 
  
  resources :reviews
  resources :restaurants do
    resources :reviews, only: [:new, :index]
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/book.rb
class Book < ApplicationRecord
    belongs_to :user
    belongs_to :genre   
    has_many :reviews
    has_many :users, through: :reviews 

    #accepts_nested_attributes_for :company

    validates :name, presence: true  
    validates :address, uniqueness: true  
    validate :not_a_duplicate 

    scope :order_by_rating, -> {left_joins(:reviews).group(:id).order('avg(stars) desc')}
    scope :most_popular, -> {left_joins(:reviews).group(:id).order('count(reviews.id) desc').limit(3)}  

    def self.alpha
        order(:name) 
    end

    def genre_attributes=(attributes)
        self.genre = Genre.find_or_create_by(attributes) if !attributes['name'].empty?
        self.genre 
    end

    def not_a_duplicate
        # if there is already a book with this name and address 
        book = Book.find_by(name: name, address: address) 
        if !!book && book != self
          errors.add(:name, 'has already been added for that address')
        end
    end 

    def genre_name
        genre.try(:name)
      end
    
      def name_and_genre
        "#{name} - #{genre.try(:name)}"
      end
 
      
end

app/controllers/books_controller.rb
class BookController < ApplicationController
    before_action :redirect_if_not_logged_in
    before_action :set_book, only: [:show, :edit, :update] 

    def new 
        @book = Book.new  
        @book.build_genre 
    end 

    def create
        @book = Book.new(book_params) 
        @book.user_id = session[:user_id] 
   
       if @book.save 
         redirect_to book_path(@book) 
       else
        @book.build_genre  
         render :new 
       end
     end

    def index   
      if params[:genre_id]
        genre = Genre.find(params[:genre_id])
        @books = genre.books 
      
      else 
        @books = Book.order_by_rating.includes(:genre) 
      end 
    end 

    def show 
    end 

    def edit 
      if authorized_to_edit?(@book) 
       render :edit   
      else 
       redirect_to book_path(@book)   
      end
     end 

    def update   
      if @book.update(book_params)
        redirect_to book_path(@book)
      else
        render :edit
      end 
    end 

    def most_popular 
      @books = Book.most_popular 
    end 

    private 

    def book_params
        params.require(:book).permit(:name, :price_range, :address, :genre_id, genre_attributes: [:name])
      end

    def set_book
        @book = Book.find_by(id: params[:id])
        redirect_to books_path if !@book 
     end

     def redirect_if_not_authorized 
      if @book.update(name: params[:name], price_range: params[:price_range], address: params[:address])   
        redirect_to book_path(@book)
      else
        redirect_to user_path(current_user)     
      end 
    end

end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= render partial: 'layouts/errors', locals: {object: @book}  %>
<%= form_for(@book) do |f|%> 
    <div>
      <%= f.label :name %>
      <%= f.text_field :name %>
    </div>
    
    <div>
      <%= f.label :price_range %> 
      <%= f.select :price_range,options_for_select(["$", "$$", "$$$"]), include_blank: true %>   
    </div>
    <div>
      <%= f.label :address %>
      <%= f.text_field :address %> 
    </div>

    <p> Select a genre that already exists: </p>
    <div>
      <%= f.collection_select :genre_id, Genre.all, :id, :name, include_blank: 'Select One'%>
  
    </div>
  
    <p> Or create a new genre: </p>
    <div>
      <%= f.fields_for :genre do |c| %>
        <%= c.label :name %>
        <%= c.text_field :name %>
      <% end %> 
    </div> 
    <br>
    <%= f.submit %>
  <% end %>

app/views/books/edit.html.erb
<h1>Edit your Restaurant</h1>



<%= render partial: 'form'%>

app/views/books/index.html.erb
<h1>All the Books</h1>
<%= form_tag('/books',:method=>:get) do %>                          
<%= select_tag "genre_id", options_from_collection_for_select(Genre.all, "id", "name", params[:genre_id]), include_blank: 'Select One' %>    
<%= submit_tag %>
<% end %>

<% @books.each do |r| %>

  <h2><%= link_to r.name, book_path(r.id)%> - <%= r.genre.name %> - <%= r.price_range %> </h2>
  <%= link_to "Write a review", new_book_review_path(r.id) %> 
  <p><%= r.address %></p>
  <% end %>

app/views/books/most_popular.html.erb
<% @restaurants.each do |r| %>
    <%= r.name %> 
    <% end %> 

app/views/books/new.html.erb
<h1>Make a New Restaurant:</h1> 


<%= render partial: 'form'%>

app/views/books/show.html.erb
<h1><%= @book.name%>  </h1>


<h2> <%= @book.category_name %> </h2>
<div>
  <p><%= @book.price_range %></p>
  <p><%= @book.address %></p>
</div>


<%= link_to "Edit #{@book.name}", edit_restaurant_path(@book) if @book.user == current_user%>

<br></br>

<%= link_to "See all Reviews", restaurant_reviews_path(@book) %>