config/routes.rb
Rails.application.routes.draw do
  
  resources :categories 
  get '/' => 'sessions#home' 
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/signup' => 'users#new' 
  post '/signup' => 'users#create' 
  delete '/logout' => 'sessions#destroy'
  get '/most_popular' => 'restaurants#most_popular' 

  get '/auth/:provider/callback' => 'sessions#create'
 
  
  resources :reviews
  resources :restaurants do
    resources :reviews, only: [:new, :index]
  end

  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_loggedin_links.html.erb
<%= link_to "Log Out", logout_path, method: :delete %> |
<%= link_to "Add a Restaurant", new_restaurant_path %> |
<%= link_to "All Restaurants", restaurants_path %> |
<%= link_to "Add a Review", new_review_path %> |
<%= link_to "All Reviews", reviews_path %> |
<%= link_to "All Genres", genres_path %> |
<%= link_to "Home", user_path(:user_id)%> 

app/views/layouts/_loggedout_links.html.erb
<%= link_to "Login", login_path %> |
<%= link_to "Signup", signup_path %> |
<%= link_to "Sign in with Facebook", "/auth/Facebook" %> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>